//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by gen. DO NOT EDIT.

package rpc

import (
	context "context"
)

// AdminCaller implements Admin via a Caller.
type AdminCaller struct {
	Caller
}

type GetpidRes struct {
	Res0 int
}

func (s *AdminCaller) Getpid() (res0 int, err error) {
	var res GetpidRes
	err = s.Caller.Call(context.Background(), "Getpid", nil, &res)
	return res.Res0, err
}

type HostnameRes struct {
	Res0 string
}

func (s *AdminCaller) Hostname() (res0 string, err error) {
	var res HostnameRes
	err = s.Caller.Call(context.Background(), "Hostname", nil, &res)
	return res.Res0, err
}

// AdminHandler implements Handler via a Admin.
type AdminHandler struct {
	Admin
}

func (h *AdminHandler) Serve(ctx context.Context, method string, stream Stream) error {
	switch method {
	case "Getpid":
		var res GetpidRes
		var err error
		res.Res0, err = h.Getpid()
		if err != nil {
			return err
		}
		if err := stream.Send(ctx, &res); err != nil {
			return err
		}
	case "Hostname":
		var res HostnameRes
		var err error
		res.Res0, err = h.Hostname()
		if err != nil {
			return err
		}
		if err := stream.Send(ctx, &res); err != nil {
			return err
		}
	default:
		return UnknownMethod(method)
	}
	return nil
}

// DiscoveryCaller implements Discovery via a Caller.
type DiscoveryCaller struct {
	Caller
}

type ListArg struct {
	Node   string
	Target string
}

type ListRes struct {
	Res0 []string
}

func (s *DiscoveryCaller) List(node string, target string) (res0 []string) {
	arg := &ListArg{
		Node:   node,
		Target: target,
	}
	var res ListRes
	err := s.Caller.Call(context.Background(), "List", arg, &res)
	if err != nil {
		panic(err)
	}
	return res.Res0
}

// DiscoveryHandler implements Handler via a Discovery.
type DiscoveryHandler struct {
	Discovery
}

func (h *DiscoveryHandler) Serve(ctx context.Context, method string, stream Stream) error {
	switch method {
	case "List":
		var arg ListArg
		if err := stream.Recv(ctx, &arg); err != nil {
			return err
		}
		var res ListRes
		res.Res0 = h.List(arg.Node, arg.Target)
		if err := stream.Send(ctx, &res); err != nil {
			return err
		}
	default:
		return UnknownMethod(method)
	}
	return nil
}
