//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by gen. DO NOT EDIT.

package test

import (
	context "context"
	iter "iter"
	strconv "strconv"

	rpc "github.com/koct9i/sand/rpc"
)

// TestCaller implements Test via a Caller.
type TestCaller struct {
	rpc.Caller
}

func (s *TestCaller) WithError() (err error) {
	return s.Caller.Call(context.Background(), "WithError", nil, nil)
}

func (s *TestCaller) WithNothing() {
	err := s.Caller.Call(context.Background(), "WithNothing", nil, nil)
	if err != nil {
		panic(err)
	}
}

type WithParamArg struct {
	Arg int
}

func (a *WithParamArg) Get(key string) string {
	switch key {
	case "Arg":
		return strconv.Itoa(a.Arg)
	default:
		return ""
	}
}

func (a *WithParamArg) Set(key, value string) error {
	switch key {
	case "Arg":
		if val, err := strconv.ParseInt(value, 0, 0); err != nil {
			return err
		} else {
			a.Arg = int(val)
		}
		return nil
	default:
		return rpc.UnknownMethod(key)
	}
}

func (s *TestCaller) WithParam(arg int) {
	arg_ := &WithParamArg{
		Arg: arg,
	}
	err := s.Caller.Call(context.Background(), "WithParam", arg_, nil)
	if err != nil {
		panic(err)
	}
}

type WithResultRes struct {
	Res0 int
}

func (s *TestCaller) WithResult() (res0 int) {
	var res_ WithResultRes
	err := s.Caller.Call(context.Background(), "WithResult", nil, &res_)
	if err != nil {
		panic(err)
	}
	return res_.Res0
}

// TestHandler implements Handler via a Test.
type TestHandler struct {
	Test
}

func (h *TestHandler) WithError(ctx context.Context, stream rpc.Stream) error {
	var err_ error
	err_ = h.Test.WithError()
	if err_ != nil {
		return err_
	}
	return nil
}

func (h *TestHandler) WithNothing(ctx context.Context, stream rpc.Stream) error {
	h.Test.WithNothing()
	return nil
}

func (h *TestHandler) WithParam(ctx context.Context, stream rpc.Stream) error {
	var arg WithParamArg
	if err := stream.Recv(ctx, &arg); err != nil {
		return err
	}
	h.Test.WithParam(arg.Arg)
	return nil
}

func (h *TestHandler) WithResult(ctx context.Context, stream rpc.Stream) error {
	var res WithResultRes
	res.Res0 = h.Test.WithResult()
	if err := stream.Send(ctx, &res); err != nil {
		return err
	}
	return nil
}

func (h *TestHandler) Methods() iter.Seq2[string, rpc.MethodFunc] {
	return func(yield func(string, rpc.MethodFunc) bool) {
		if !yield("WithError", h.WithError) {
			return
		}
		if !yield("WithNothing", h.WithNothing) {
			return
		}
		if !yield("WithParam", h.WithParam) {
			return
		}
		if !yield("WithResult", h.WithResult) {
			return
		}
	}
}

func (h *TestHandler) Serve(ctx context.Context, method string, stream rpc.Stream) error {
	switch method {
	case "WithError":
		return h.WithError(ctx, stream)
	case "WithNothing":
		return h.WithNothing(ctx, stream)
	case "WithParam":
		return h.WithParam(ctx, stream)
	case "WithResult":
		return h.WithResult(ctx, stream)
	default:
		return rpc.UnknownMethod(method)
	}
}
